#!/bin/bash

# Script written/developed by Matt Trotter sudirlay@icloud.com

clear

echo "Please choose an option by typing the letter"
echo "(a) Fix sidebar/contact menu not displaying correctly"
echo "(b) Fix/Update all plugins"
echo "(c) Clean the blog's malicious php header code"
echo "(d) List all blog's plugins"
echo "(e) Verify virtual host entry is activated and correct"
echo "(f) Backup any number of blogs"
echo "(g) Push wp-security and broken-link-chercker plugin"
echo "(h) Correct htaccess file"
echo "(i) Correct CSS Header change (alert only done during deployment)"

read answer

# Fix for sidebar
if [ "$answer" == a ]

then 

echo "Which blog id's do you want to correct sidebar issues for?"
read id

echo $id > /usr/local/bin/blog_ids.txt
readarray -t array </usr/local/bin/blog_ids.txt

echo "Fixing the following blog ids now"
cat blog_ids.txt

for i in  ${array[*]}
do
mv -fr /var/www/blogs/$i/wp-content/themes/xxx /var/www/blogs/$i/wp-content/themes/xxx
mv -fr /var/www/blogs/$i/wp-content/themes/xxx /var/www/blogs/$i/wp-content/themes/xxx
cp -fr /root/sidebarfix/* /var/www/blogs/$i/wp-content/themes/

clear
done
echo "done!!!!"

# Fix for youtube plugin outdated

                elif  [ "$answer" == b ]

then       
echo "Enter blog id numbers you want to update/correct plugins for"
read id2

echo $id2 > /usr/local/bin/blog_ids.txt
readarray -t array </usr/local/bin/blog_ids.txt
for i in  ${array[*]}
do

echo "You are currently running these plugins" >>plugin.log
cd /var/www/blogs/$i/
/usr/local/bin/mat plugin list --all --allow-root >> plugin.log
/usr/local/bin/mat plugin update --all --allow-root 
/usr/local/bin/mat plugin activate youtube-embed-plus --allow-root
echo "done!!!"
echo "You are currently running these plugins now after update">>plugin.log
/usr/local/bin/mat plugin list --allow-root >>plugin.log

done

# Fix for cleaning the php malicious header code

elif [ "$answer" == c ]

   then 

/usr/local/bin/clean




elif
[ "$answer" == d ]

then 
echo "Enter blog id do you wish to view plugins for:"
read plugins

cd /var/www/blogs/$plugins/
clear
echo "The folloing plugins for blog_$plugins are:"
/usr/local/bin/mat plugin list --allow-root



                    elif

                [ "$answer" == e ]


then

echo "Enter domain name or blog ID would you like to verify virtual host entry for? (FYI doesnt have to be the full name)"
read vhost

cat /etc/apache2/sites-available/default | grep $vhost
elif
          [ "$answer" == f ]

then
echo "Enter blog id's you want to backup, as many as you like" 
read backup

clear

echo "Backing up blogs now...."
sleep 1

echo $backup > /usr/local/bin/backup.txt
readarray -t array </usr/local/bin/backup.txt

for i in ${array[*]}
do

cp -R /var/www/blogs/$i/ /root/backup/


clear
done
echo "done!"



elif
          [ "$answer" == g ]

then
echo "Enter blog id's you want to push wp-security and broken-link-checker to, enter as many as you like" 
read push

clear

echo "Pushing plugins now...."
sleep 1

echo $push > /usr/local/bin/backup.txt
readarray -t array </usr/local/bin/backup.txt

for i in ${array[*]}
do

cd /var/www/blogs/$i/
/usr/local/bin/mat plugin deactivate broken-link-checker --allow-root
/usr/local/bin/mat plugin uninstall broken-link-checker --allow-root 
/usr/local/bin/mat plugin install wp-security-scan broken-link-checker --allow-root
/usr/local/bin/mat plugin activate wp-security-scan broken-link-checker --allow-root
done

elif
       [ "$answer" == h ]
then 
   echo "Enter blog ids you would like to correct htaccess files for"
read ht

clear
echo "Fixing ht access files now..."
sleep 1
echo $ht > /usr/local/bin/backup.txt
readarray -t array </usr/local/bin/backup.txt

for i in ${array[*]} 
do

cp -fr /root/.fix /var/www/blogs/$i/.htaccess

done

echo "Finished.. :-)"


elif
       [ "$answer" == i ]

then
   echo "Enter blog ids you would like to run the css header change for"
read cs

clear
echo "Changing css header files now..."
sleep 1
echo $cs > /usr/local/bin/backup.txt
readarray -t array </usr/local/bin/backup.txt

for i in ${array[*]}
do
clear
echo "Changing responsive header file"
grep -rl header /var/www/blogs/$i/wp-content/themes/xxx | xargs sed -i 's/oldthing/newthing'
cd /var/www/blogs/$i/wp-content/themes/xxx
echo "blog_$i's new header file is:" >> header.log
cat header.php >>header.log
sleep 3

clear
echo "A log of this change has been recorded in /$i/header.log"
done
fi
echo "done exiting"








