#!/bin/bash

# script written/developed by: Matthew Trotter sudirlay@icloud.com 
# This is a script to clean and change doadmin username and passwords on any blog id specified.
# The joint efforts of payam and matt trotter have been consolidted into this one script
# Simply enter the blog id and let it fire
clear




echo "Greetings, enter the Blog-ID numbers you wish to clean, as many as you need:"
read number

echo $number > /usr/local/bin/blog_ids.txt
readarray -t array </usr/local/bin/blog_ids.txt

for i in ${array[*]}
do
clear

echo "You are currently in directory $i" 
sleep 2

cd /var/www/blogs/$i

clear
echo "You are now in directory /var/www/blogs/$i"
sleep 3
clear

echo "Scanning the directory..."
sudo bash /usr/local/bin/findcrap  > /dev/null 2>&1
clear

echo "Heres what the scan found:"
sleep 2
cat temp.txt


sleep 1
clear
echo "Removing the malicious items now......"
php /usr/local/bin/remove_crap2.php > /dev/null 2>&1 

rm -fr temp.txt

sudo bash /usr/local/bin/findcrap  > /dev/null 2>&1
sleep 3
clear

echo "Cleanup done, the following items are left:"
sleep 1
cat temp.txt

sleep 2
clear
echo "bye..."

done




