#!/bin/bash
# script written/developed by: Matthew Trotter sudirlay@icloud.com
# This is a script to backup important files before we begin deployment tonight
clear

echo "Please enter the blog ids one after another to backup"
read id1



clear
echo "next id"
read id2


clear
echo "next id"
read id3


clear
echo "next id"
read id4

clear
echo "next id"
read id5

echo "Currently backing the following blogs..$id1 $id2 $id3 $id4 $id5"
mkdir /root/backup

cp -R /var/www/blogs/$id1 /root/backup/
cp -R /var/www/blogs/$id2 /root/backup/
cp -R /var/www/blogs/$id3 /root/backup/
cp -R /var/www/blogs/$id4 /root/backup/
cp -R /var/www/blogs/$id4 /root/backup/

clear
echo "All blogs backed up, backing up apache2 virtual host conf file":

cp /etc/apache2/sites-available/default /etc/apache2/sites-available/default.bckup

